config/routes.rb
Reisekosten::Application.routes.draw do
  resources :belegs

  resources :nachweises

  resources :verpflegungsmehraufwands

  resources :pauschale_typs

  resources :pauschales

  resources :reises

  resources :verpflegungs

  root :to => 'reises#index'

end

app/controllers/reises_controller.rb
class ReisesController < ApplicationController

  #caches_page :index, :show

  #active_scaffold :document do |config|
  #  config.columns = [ :id, :product, :title, :document_type, :author, :organization, :document_approver, :document_location ]
  #  config.list.columns.exclude :organization, :document_approver, :document_location
  #  config.show.columns.exclude :id
  #  config.create.columns.exclude :id, :author, :organization
  #  config.update.columns.exclude :id, :author
  #end

  # GET /reises
  # GET /reises.json
  def index
    @reises = Reise.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reises }
    end
  end

  # GET /reises/1
  # GET /reises/1.json
  def show
    @reise = Reise.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reise }
    end
  end

  # GET /reises/new
  # GET /reises/new.json
  def new
    @reise = Reise.new
    @reise.ankunft = 0
    @reise.abreise = 0

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reise }
    end
  end

  # GET /reises/1/edit
  def edit
    @reise = Reise.find(params[:id])
  end

  # POST /reises
  # POST /reises.json
  def create
    @reise = Reise.new(params[:reise])

    respond_to do |format|

      if ((@reise.abreise - @reise.ankunft) / 1.day).to_i > 365
        flash.now[:error] = "Reise zu lang"
        render action: "new"
        return
      end

      # TODO: "Negative" Tagesreisen mit abfangen!!!
      if ((@reise.abreise - @reise.ankunft) / 1.day).to_i < 0
        flash.now[:error] = "Das Abreisedatum liegt vor dem Ankunftsdatum"
        render action: "new"
        return
      end

      if ( @reise.abreise.year.to_i < 1970 ) || ( @reise.ankunft.year.to_i < 1970 )
        flash.now[:error] = "Das angegebene Datum darf nicht vor dem 01.01.1970 liegen"
        render action: "new"
        return
      end

      if @reise.save

        ##Rails.logger.debug("reisekosten [DEBUG] " + @reise.inspect)
        #for i in 1..((@reise.abreise - @reise.ankunft) / 1.day)
        #  @verpflegungsmehraufwand = Verpflegungsmehraufwand.new
        #  @verpflegungsmehraufwand.reise_id = @reise._id
        #  @verpflegungsmehraufwand.save
        #end

        format.html { redirect_to :action => "index", notice: 'Reise was successfully created.' }
        format.json { render json: @reise, status: :created, location: @reise }
      else
        format.html { render action: "new" }
        format.json { render json: @reise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reises/1
  # PUT /reises/1.json
  def update
    @reise = Reise.find(params[:id])

    respond_to do |format|

      # TODO: !!!
      #if ((@reise.abreise - @reise.ankunft) / 1.day).to_i > 365
      #  flash.now[:error] = "Reise zu lang"
      #  render action: "edit"
      #  return
      #end

      # TODO: Die Abfragen aus 'create' auch hier uebernehmen!!!

      if @reise.update_attributes(params[:reise])
        format.html { redirect_to :action => "index", notice: 'Reise was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reises/1
  # DELETE /reises/1.json
  def destroy
    @reise = Reise.find(params[:id])
    @reise.destroy

    respond_to do |format|
      format.html { redirect_to reises_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/reises_helper.rb
module ReisesHelper
end

app/views/reises/_form.html.haml
= form_for @reise, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :grund, "Reisegrund", :class => 'control-label'
    .controls
      = f.text_field :grund, :class => 'text_field'
  .control-group
    = f.label :ankunft, :class => 'control-label'
    .controls
      #datetimepickerAnkunft.input-append.date
        %input#reise_ankunft{:value => @reise.ankunft.strftime('%Y-%m-%d %I:%M:%S'), :name => "reise[ankunft]", "data-format" => "yyyy-MM-dd hh:mm:ss", :type => "text"}
          %span.add-on
            %i{"data-date-icon" => "icon-calendar", "data-time-icon" => "icon-time"}
  .control-group
    = f.label :abreise, :class => 'control-label'
    .controls
      #datetimepickerAbreise.input-append.date
        %input#reise_abreise{:value => @reise.abreise.strftime('%Y-%m-%d %I:%M:%S'), :name => "reise[abreise]", "data-format" => "yyyy-MM-dd hh:mm:ss", :type => "text"}
          %span.add-on
            %i{"data-date-icon" => "icon-calendar", "data-time-icon" => "icon-time"}
  .control-group
    = f.label :privatPkw, "privater PKW", :class => 'control-label'
    .controls
      = f.check_box :privatPkw, :class => 'check_box'
  .control-group
    = f.label :kilometer, :class => 'control-label'
    .controls
      = f.text_field :kilometer, :class => 'text_field'
  .control-group
    = f.label :weitereFahrtkosten, "weitere Fahrtkosten", :class => 'control-label'
    .controls
      = f.text_field :weitereFahrtkosten, :class => 'text_field'
  .control-group
    = f.label :betrag, :class => 'control-label'
    .controls
      = f.text_field :betrag, :class => 'text_field'
  .control-group
    = f.label :uebernachtungskosten, "Übernachtungskosten", :class => 'control-label'
    .controls
      = f.text_field :uebernachtungskosten, :class => 'text_field'
  .control-group
    = f.label :uebernachtungInklFruehstueck, "inkl. Frühstück", :class => 'control-label'
    .controls
      = f.check_box :uebernachtungInklFruehstueck, :class => 'check_box'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), reises_path, :class => 'btn'

app/views/reises/edit.html.haml
- model_class = Reise
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/reises/index.html.haml
- model_class = Reise
.page-header
  %h1 Reisen
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:grund)
      %th= model_class.human_attribute_name(:ankunft)
      %th= model_class.human_attribute_name(:abreise)
      %th privater PKW
      %th= model_class.human_attribute_name(:kilometer)
      %th weitere Fahrtkosten
      %th= model_class.human_attribute_name(:betrag)
      %th &Uuml;bernachtungskosten
      %th inkl. Fr&uuml;hst&uuml;ck
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @reises.each do |reise|
      %tr
        %td= reise.grund
        %td= reise.ankunft
        %td= reise.abreise
        %td= true_false_image reise.privatPkw
        %td= reise.kilometer
        %td= reise.weitereFahrtkosten
        %td= reise.betrag
        %td= reise.uebernachtungskosten
        %td= true_false_image reise.uebernachtungInklFruehstueck
        %td
          = link_to t('.beleg', :default => t("helpers.links.beleg")), beleg_path(reise).to_s + '.pdf', :class => 'btn btn-mini'
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_reise_path(reise), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), reise_path(reise), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_reise_path, :class => 'btn btn-primary'

app/views/reises/new.html.haml
- model_class = Reise
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/reises/show.html.haml
- model_class = Reise
.page-header
  %h1=t '.title', :default => model_class.model_name.human
%p
  %strong= model_class.human_attribute_name(:grund) + ':'
  %br
  = @reise.grund
%p
  %strong= model_class.human_attribute_name(:ankunft) + ':'
  %br
  = @reise.ankunft
%p
  %strong= model_class.human_attribute_name(:abreise) + ':'
  %br
  = @reise.abreise
%p
  %strong= model_class.human_attribute_name(:privatPkw) + ':'
  %br
  = true_false_image @reise.privatPkw
%p
  %strong= model_class.human_attribute_name(:kilometer) + ':'
  %br
  = @reise.kilometer
%p
  %strong= model_class.human_attribute_name(:weitereFahrtkosten) + ':'
  %br
  = @reise.weitereFahrtkosten
%p
  %strong= model_class.human_attribute_name(:betrag) + ':'
  %br
  = @reise.betrag
%p
  %strong= model_class.human_attribute_name(:uebernachtungskosten) + ':'
  %br
  = @reise.uebernachtungskosten
%p
  %strong= model_class.human_attribute_name(:uebernachtungInklFruehstueck) + ':'
  %br
  = true_false_image @reise.uebernachtungInklFruehstueck

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), reises_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_reise_path(@reise), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), reise_path(@reise), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'