config/routes.rb
Reisekosten::Application.routes.draw do
  resources :belegs

  resources :nachweises

  resources :verpflegungsmehraufwands

  resources :pauschale_typs

  resources :pauschales

  resources :reises

  resources :verpflegungs

  root :to => 'reises#index'

end

app/models/beleg.rb
class Beleg
  include Mongoid::Document 
  field :summeUebernachtung, type: Money
  field :summeVerpflegung, type: Money
  field :summeNebenkosten, type: Money
  field :summeGesamt, type: Money

  field :summeReisekosten, type: Money
  field :summeKilometergeld, type: Money
end

app/controllers/belegs_controller.rb
class BelegsController < ApplicationController

  def show
    @beleg = Beleg.new
    @beleg.summeUebernachtung = Money.new(0)
    @beleg.summeVerpflegung = Money.new(0)
    @beleg.summeNebenkosten = Money.new(0)
    @beleg.summeGesamt = Money.new(0)
    @beleg.summeReisekosten = Money.new(0)

    @reise = Reise.find(params[:id])

    if @reise.privatPkw == true
      @beleg.summeKilometergeld = Money.new(@reise.kilometer * 100 * 0.3)
    else
      @beleg.summeKilometergeld = Money.new(0)
    end

    @belegpositionen = Array.new

    for i in 0..((@reise.abreise - @reise.ankunft) / 1.day)
      @belegposition = Belegposition.new

      @belegposition.uebernachtung = Money.new(0)
      @belegposition.verpflegung = Money.new(0)
      @belegposition.nebenkosten = Money.new(0)

      @belegposition.datum = @reise.ankunft + i.days

      if Date.new(@belegposition.datum.year, @belegposition.datum.month, @belegposition.datum.day) == Date.new(@reise.abreise.year, @reise.abreise.month, @reise.abreise.day)
        @belegposition.stunden = @reise.abreise.hour
        @belegposition.uebernachtung = 0
      else
        if Date.new(@belegposition.datum.year, @belegposition.datum.month, @belegposition.datum.day) == Date.new(@reise.ankunft.year, @reise.ankunft.month, @reise.ankunft.day)
          @belegposition.stunden = 24 - @reise.ankunft.hour
        else
          @belegposition.stunden = 24;
        end

        if @reise.uebernachtungInklFruehstueck == true
          if @reise.uebernachtungskosten < Money.new(700)
            @belegposition.uebernachtung = @reise.uebernachtungskosten
          else
            @belegposition.uebernachtung =  Money.new(@reise.uebernachtungskosten * 100) - Money.new(700)
          end
        else
          @belegposition.uebernachtung = @reise.uebernachtungskosten
        end
      end

      @belegposition.nebenkosten = Money.new(0)

      @beleg.summeUebernachtung += Money.new(@belegposition.uebernachtung * 100)
      @beleg.summeVerpflegung += Money.new(@belegposition.verpflegung * 100)
      @beleg.summeNebenkosten += Money.new(@belegposition.nebenkosten * 100)

      @belegposition.summe = Money.new((@belegposition.uebernachtung + @belegposition.verpflegung + @belegposition.nebenkosten) * 100)

      @beleg.summeGesamt = Money.new((@beleg.summeUebernachtung + @beleg.summeVerpflegung + @beleg.summeNebenkosten) * 100)

      @belegpositionen << @belegposition
    end

      @beleg.summeReisekosten = Money.new((@beleg.summeGesamt + @beleg.summeKilometergeld + @reise.betrag) * 100)

    respond_to do |format|
      format.html
      format.pdf do
        render :pdf           => @reise.id.to_s,
               #:template      => 'belegs/show.pdf.haml',
               :layout        => 'pdf',
               #:footer        => { :right => '[page] von [topage]' },
               #:save_to_file => Rails.root.join('pdfs', "#{@user.name}.pdf")
               :show_as_html => params[:debug].present?
      end
    end
  end

  ## GET /belegs/1
  ## GET /belegs/1.json
  #def show
  #  @beleg = Beleg.find(params[:id])

  #  respond_to do |format|
  #    format.html # show.html.erb
  #    format.json { render json: @beleg }
  #  end
  #end

end

app/helpers/belegs_helper.rb
module BelegsHelper
end

app/views/belegs/_form.html.haml
= form_for @beleg, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :_id, :class => 'control-label'
    .controls
      = f.text_field :_id, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), belegs_path, :class => 'btn'

app/views/belegs/edit.html.haml
- model_class = Beleg
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/belegs/index.html.haml
- model_class = Beleg
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:_id)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @belegs.each do |beleg|
      %tr
        %td= link_to beleg.id, beleg_path(beleg)
        %td= beleg._id
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_beleg_path(beleg), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), beleg_path(beleg), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_beleg_path, :class => 'btn btn-primary'

app/views/belegs/new.html.haml
- model_class = Beleg
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/belegs/show.pdf.haml
- model_class = Belegposition

%p
  %strong Name:
  {Name}

%br

%p
  %strong Reisegrund:
  = @reise.grund
%p
  %strong Abreise:
  = @reise.abreise
%p
  %strong Ankunft:
  = @reise.ankunft
%p
  %strong Tage:
  = (((@reise.abreise - @reise.ankunft) / 1.days) + 1).to_i

%br

%h2 Fahrtkosten
%p
  %strong PKW-km:
  = @reise.kilometer

  %strong Betrag:
  = @beleg.summeKilometergeld
%p
  %strong Anderweitige Fahrkosten:
  = @reise.weitereFahrtkosten

  %strong Betrag:
  = @reise.betrag

%br
%br

%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:datum)
      %th= model_class.human_attribute_name(:stunden)
      %th  &Uuml;bernachtung
      %th= model_class.human_attribute_name(:verpflegung)
      %th= model_class.human_attribute_name(:nebenkosten)
      %th= model_class.human_attribute_name(:summe)
  %tbody
    - @belegpositionen.each do |position|
      %tr
        %td= position.datum
        %td= position.stunden
        %td= position.uebernachtung
        %td= position.verpflegung
        %td= position.nebenkosten
        %td= position.summe
    %tr
      %td 
      %td
      %td
        %strong= @beleg.summeUebernachtung
      %td
        %strong= @beleg.summeVerpflegung
      %td
        %strong= @beleg.summeNebenkosten
      %td
        %strong= @beleg.summeGesamt
    %tr
      %td
      %td
      %td
      %td
      %td
      %td
    %tr
      %td 
        %strong Reisekosten gesamt
      %td
      %td
      %td
      %td
      %td
        %strong= @beleg.summeReisekosten