config/routes.rb
Reisekosten::Application.routes.draw do
  resources :belegs

  resources :nachweises

  resources :verpflegungsmehraufwands

  resources :pauschale_typs

  resources :pauschales

  resources :reises

  resources :verpflegungs

  root :to => 'reises#index'

end

app/models/pauschale.rb
class Pauschale
  include Mongoid::Document
  field :stunden, type: Integer
  field :betrag, type: Money
  field :typ, type: Integer
end

app/controllers/pauschales_controller.rb
class PauschalesController < ApplicationController
  # GET /pauschales
  # GET /pauschales.json
  def index
    @pauschales = Pauschale.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pauschales }
    end
  end

  # GET /pauschales/1
  # GET /pauschales/1.json
  def show
    @pauschale = Pauschale.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pauschale }
    end
  end

  # GET /pauschales/new
  # GET /pauschales/new.json
  def new
    @pauschale = Pauschale.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pauschale }
    end
  end

  # GET /pauschales/1/edit
  def edit
    @pauschale = Pauschale.find(params[:id])
  end

  # POST /pauschales
  # POST /pauschales.json
  def create
    @pauschale = Pauschale.new(params[:pauschale])

    respond_to do |format|
      if @pauschale.save
        format.html { redirect_to :action => "index", notice: 'Pauschale was successfully created.' }
        format.json { render json: @pauschale, status: :created, location: @pauschale }
      else
        format.html { render action: "new" }
        format.json { render json: @pauschale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pauschales/1
  # PUT /pauschales/1.json
  def update
    @pauschale = Pauschale.find(params[:id])

    respond_to do |format|
      if @pauschale.update_attributes(params[:pauschale])
        format.html { redirect_to :action => "index", notice: 'Pauschale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pauschale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pauschales/1
  # DELETE /pauschales/1.json
  def destroy
    @pauschale = Pauschale.find(params[:id])
    @pauschale.destroy

    respond_to do |format|
      format.html { redirect_to pauschales_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pauschales_helper.rb
module PauschalesHelper
end

app/views/pauschales/_form.html.haml
= form_for @pauschale, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :stunden, :class => 'control-label'
    .controls
      = f.text_field :stunden, :class => 'text_field'
  .control-group
    = f.label :betrag, :class => 'control-label'
    .controls
      = f.text_field :betrag, :class => 'text_field'
  .control-group
    = f.label :typ, :class => 'control-label'
    .controls
      = f.text_field :typ, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), pauschales_path, :class => 'btn'

app/views/pauschales/edit.html.haml
- model_class = Pauschale
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/pauschales/index.html.haml
- model_class = Pauschale
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:stunden)
      %th= model_class.human_attribute_name(:betrag)
      %th= model_class.human_attribute_name(:typ)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @pauschales.each do |pauschale|
      %tr
        %td= pauschale.stunden
        %td= pauschale.betrag
        %td= pauschale.typ
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_pauschale_path(pauschale), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), pauschale_path(pauschale), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_pauschale_path, :class => 'btn btn-primary'

app/views/pauschales/new.html.haml
- model_class = Pauschale
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/pauschales/show.html.haml
- model_class = Pauschale
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:_id) + ':'
  %br
  = @pauschale._id
%p
  %strong= model_class.human_attribute_name(:stunden) + ':'
  %br
  = @pauschale.stunden
%p
  %strong= model_class.human_attribute_name(:betrag) + ':'
  %br
  = @pauschale.betrag
%p
  %strong= model_class.human_attribute_name(:typ) + ':'
  %br
  = @pauschale.typ

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), pauschales_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_pauschale_path(@pauschale), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), pauschale_path(@pauschale), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'