config/routes.rb
Reisekosten::Application.routes.draw do
  resources :belegs

  resources :nachweises

  resources :verpflegungsmehraufwands

  resources :pauschale_typs

  resources :pauschales

  resources :reises

  resources :verpflegungs

  root :to => 'reises#index'

end

app/models/verpflegungsmehraufwand.rb
class Verpflegungsmehraufwand
  include Mongoid::Document
  field :reise_id, type: Mongoid
  field :datum, type: Date
  field :stunden, type: Integer
  field :nachweis, type: Nachweise
  field :ersparnis, type: Money
  field :maxBetrag, type: Money
  field :nachweisBetrag, type: Money
  field :pauschale, type: Money

  validates_presence_of :reise_id
end

app/controllers/verpflegungsmehraufwands_controller.rb
class VerpflegungsmehraufwandsController < ApplicationController
  # GET /verpflegungsmehraufwands
  # GET /verpflegungsmehraufwands.json
  def index
    @verpflegungsmehraufwands = Verpflegungsmehraufwand.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @verpflegungsmehraufwands }
    end
  end

  # GET /verpflegungsmehraufwands/1
  # GET /verpflegungsmehraufwands/1.json
  def show
    @verpflegungsmehraufwand = Verpflegungsmehraufwand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @verpflegungsmehraufwand }
    end
  end

  # GET /verpflegungsmehraufwands/new
  # GET /verpflegungsmehraufwands/new.json
  def new
    @verpflegungsmehraufwand = Verpflegungsmehraufwand.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @verpflegungsmehraufwand }
    end
  end

  # GET /verpflegungsmehraufwands/1/edit
  def edit
    @verpflegungsmehraufwand = Verpflegungsmehraufwand.find(params[:id])
  end

  # POST /verpflegungsmehraufwands
  # POST /verpflegungsmehraufwands.json
  def create
    @verpflegungsmehraufwand = Verpflegungsmehraufwand.new(params[:verpflegungsmehraufwand])

    respond_to do |format|
      if @verpflegungsmehraufwand.save
        format.html { redirect_to @verpflegungsmehraufwand, notice: 'Verpflegungsmehraufwand was successfully created.' }
        format.json { render json: @verpflegungsmehraufwand, status: :created, location: @verpflegungsmehraufwand }
      else
        format.html { render action: "new" }
        format.json { render json: @verpflegungsmehraufwand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /verpflegungsmehraufwands/1
  # PUT /verpflegungsmehraufwands/1.json
  def update
    @verpflegungsmehraufwand = Verpflegungsmehraufwand.find(params[:id])

    respond_to do |format|
      if @verpflegungsmehraufwand.update_attributes(params[:verpflegungsmehraufwand])
        format.html { redirect_to @verpflegungsmehraufwand, notice: 'Verpflegungsmehraufwand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @verpflegungsmehraufwand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /verpflegungsmehraufwands/1
  # DELETE /verpflegungsmehraufwands/1.json
  def destroy
    @verpflegungsmehraufwand = Verpflegungsmehraufwand.find(params[:id])
    @verpflegungsmehraufwand.destroy

    respond_to do |format|
      format.html { redirect_to verpflegungsmehraufwands_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/verpflegungsmehraufwands_helper.rb
module VerpflegungsmehraufwandsHelper
end

app/views/verpflegungsmehraufwands/_form.html.haml
= form_for @verpflegungsmehraufwand, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :_id, :class => 'control-label'
    .controls
      = f.text_field :_id, :class => 'text_field'
  .control-group
    = f.label :reise_id, :class => 'control-label'
    .controls
      = f.text_field :reise_id, :class => 'text_field'
  .control-group
    = f.label :datum, :class => 'control-label'
    .controls
      = f.text_field :datum, :class => 'text_field'
  .control-group
    = f.label :stunden, :class => 'control-label'
    .controls
      = f.text_field :stunden, :class => 'text_field'
  .control-group
    = f.label :nachweis, :class => 'control-label'
    .controls
      = f.text_field :nachweis, :class => 'text_field'
  .control-group
    = f.label :ersparnis, :class => 'control-label'
    .controls
      = f.text_field :ersparnis, :class => 'text_field'
  .control-group
    = f.label :maxBetrag, :class => 'control-label'
    .controls
      = f.text_field :maxBetrag, :class => 'text_field'
  .control-group
    = f.label :nachweisBetrag, :class => 'control-label'
    .controls
      = f.text_field :nachweisBetrag, :class => 'text_field'
  .control-group
    = f.label :pauschale, :class => 'control-label'
    .controls
      = f.text_field :pauschale, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), verpflegungsmehraufwands_path, :class => 'btn'

app/views/verpflegungsmehraufwands/edit.html.haml
- model_class = Verpflegungsmehraufwand
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/verpflegungsmehraufwands/index.html.haml
- model_class = Verpflegungsmehraufwand
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:_id)
      %th= model_class.human_attribute_name(:reise_id)
      %th= model_class.human_attribute_name(:datum)
      %th= model_class.human_attribute_name(:stunden)
      %th= model_class.human_attribute_name(:nachweis)
      %th= model_class.human_attribute_name(:ersparnis)
      %th= model_class.human_attribute_name(:maxBetrag)
      %th= model_class.human_attribute_name(:nachweisBetrag)
      %th= model_class.human_attribute_name(:pauschale)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @verpflegungsmehraufwands.each do |verpflegungsmehraufwand|
      %tr
        %td= link_to verpflegungsmehraufwand.id, verpflegungsmehraufwand_path(verpflegungsmehraufwand)
        %td= verpflegungsmehraufwand._id
        %td= verpflegungsmehraufwand.reise_id
        %td= verpflegungsmehraufwand.datum
        %td= verpflegungsmehraufwand.stunden
        %td= verpflegungsmehraufwand.nachweis
        %td= verpflegungsmehraufwand.ersparnis
        %td= verpflegungsmehraufwand.maxBetrag
        %td= verpflegungsmehraufwand.nachweisBetrag
        %td= verpflegungsmehraufwand.pauschale
        %td=l verpflegungsmehraufwand.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_verpflegungsmehraufwand_path(verpflegungsmehraufwand), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), verpflegungsmehraufwand_path(verpflegungsmehraufwand), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_verpflegungsmehraufwand_path, :class => 'btn btn-primary'

app/views/verpflegungsmehraufwands/new.html.haml
- model_class = Verpflegungsmehraufwand
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/verpflegungsmehraufwands/show.html.haml
- model_class = Verpflegungsmehraufwand
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:_id) + ':'
  %br
  = @verpflegungsmehraufwand._id
%p
  %strong= model_class.human_attribute_name(:reise_id) + ':'
  %br
  = @verpflegungsmehraufwand.reise_id
%p
  %strong= model_class.human_attribute_name(:datum) + ':'
  %br
  = @verpflegungsmehraufwand.datum
%p
  %strong= model_class.human_attribute_name(:stunden) + ':'
  %br
  = @verpflegungsmehraufwand.stunden
%p
  %strong= model_class.human_attribute_name(:nachweis) + ':'
  %br
  = @verpflegungsmehraufwand.nachweis
%p
  %strong= model_class.human_attribute_name(:ersparnis) + ':'
  %br
  = @verpflegungsmehraufwand.ersparnis
%p
  %strong= model_class.human_attribute_name(:maxBetrag) + ':'
  %br
  = @verpflegungsmehraufwand.maxBetrag
%p
  %strong= model_class.human_attribute_name(:nachweisBetrag) + ':'
  %br
  = @verpflegungsmehraufwand.nachweisBetrag
%p
  %strong= model_class.human_attribute_name(:pauschale) + ':'
  %br
  = @verpflegungsmehraufwand.pauschale

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), verpflegungsmehraufwands_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_verpflegungsmehraufwand_path(@verpflegungsmehraufwand), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), verpflegungsmehraufwand_path(@verpflegungsmehraufwand), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'